### ISSUE TITLE
Read data is returning null

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#202]
Hi,

I am trying to replicate a workflow here (id **1647**), but the operation **Read data** is returning null:

Data source  **1186**:
![image](https://user-images.githubusercontent.com/24958541/84575733-e9069600-ad85-11ea-977f-ae5a2d200033.png)

Data source **1187**:
![image](https://user-images.githubusercontent.com/24958541/84575763-1d7a5200-ad86-11ea-8f97-045a1b8c9e55.png)

Job **11644**:
![image](https://user-images.githubusercontent.com/24958541/84575783-439ff200-ad86-11ea-8a09-db3172a8fb7f.png)

Where **Read data 0** is for the Data source 1187.

Thanks in advance.

Alex de Sá

**Comment by alexgcsa** [comment]
Hi,

A similar issue happened again in a student workflow (**2048**)

![image](https://user-images.githubusercontent.com/24958541/85932015-f439e580-b89e-11ea-89e0-24c870dcbae4.png)

Not sure why this is happening.

Thanks in advance.

Alex de Sá

**Comment by alexgcsa** [comment]
@lucasmsp , 

I have just sent you the dataset and the json of the workflow. 

I will upload here as well:

[LEMONADE_Workflow.zip](https://github.com/eubr-bigsea/citrus/files/4927273/LEMONADE_Workflow.zip)

I am not sure if this issue is a temporary problem or if it's related to the dataset. In the workflow:

Ler dados 0:  pib_populacao.csv
Ler dados 1: razao_dep.csv

Thanks in advance.

Cheers,

Alex

**Comment by lucasmsp** [comment]
Hi @alexgcsa, the problem is that the attributes were wrong inferred by Lemonade. When you insert a dataset into Lemonade, Limonero samples the data to find the most likely data type. In the case of your base, it infers that the data type would be Decimal type, however, the best option would be Long or Double type (http://spark.apache.org/docs/2.4.0/sql-reference.html).

Spark requires that each column has only one data type (cells that could not be cast in this type will be null). In your base, the first column (PIB) has big integers that could be cast as Long type, except the 3rd record (1.97826E+015) that by definition, is equivalent as "1978260000000000.0" (a double). 

Based on this, you have some options: 

- Change the 3rd record to 1978260000000000 and re-insert the data (in this case, Lemonade will infer this column as Long);
- Change the first column to "Double" in Lemonade Data sources;
- Select the option "Infer data source schema" to be based on the data while reading the file.

**Comment by alexgcsa** [comment]
Thanks a lot, @lucasmsp.

I will check these options here. 

Cheers,

Alex de Sá
